version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.7.0

    steps:
      - checkout
        
      - run: 
          name: 'Install Dependencies'
          command: | 
            sudo apt-get install -y libgtk-3-0 libxss1 libgconf2-4 libnss3 libasound2 icnsutils graphicsmagick software-properties-common apt-transport-https
        
      - run: 
          name: 'Install Wine'
          command: | 
            sudo apt-add-repository http://dl.winehq.org/wine-builds/ubuntu/
            wget -nc https://dl.winehq.org/wine-builds/Release.key && sudo apt-key add Release.key
            sudo apt-get update
            sudo apt-get install --install-recommends winehq-devel

      - restore_cache:
          keys:
          - node-modules-{{ checksum "package.json" }}

      - run:
          name: 'NPM Install'
          command: |
            npm install

      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}

      - run:
          name: 'Build Windows Package'
          command: |
            npm run pack:win
            mv dist dist-win

      - store_artifacts:
          path: dist-win

      - run:
          name: 'Build Windows Package'
          command: |
            npm run pack:mac
            mv dist dist-osx

      - store_artifacts:
          path: dist-osx