version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.7.0

    steps:
      - checkout
        
      - run: 
          name: 'Install Dependencies'
          command: | 
            sudo apt-get install -y libgtk-3-0 libxss1 libgconf2-4 libnss3 libasound2 icnsutils graphicsmagick software-properties-common
        
      - run: 
          name: 'Install Wine'
          command: | 
            sudo dpkg --add-architecture i386
            sudo add-apt-repository -y ppa:wine/wine-builds
            sudo apt-get update
            sudo apt-get install -y --install-recommends wine-staging

      - restore_cache:
          keys:
          - node-modules-{{ checksum "package.json" }}

      - run:
          name: 'NPM Install'
          command: |
            npm install

      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}

      - run:
          name: 'Build Windows Package'
          command: |
            npm run pack:win
            mv dist dist-win

      - store_artifacts:
          path: dist-win

      - run:
          name: 'Build Windows Package'
          command: |
            npm run pack:mac
            mv dist dist-osx

      - store_artifacts:
          path: dist-osx